<a href="https://colab.research.google.com/github/BhanuPrakash-Guniganti/python-for-ml/blob/main/House_Price_Predection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import pandas as pd

In [95]:
home=pd.read_csv('/content/House Price Prediction Dataset.csv')

In [96]:
home

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [97]:
x=home[['Area', 'Bathrooms', 'Bedrooms', 'Floors' ]]
y=home['Price']

In [98]:
y

0       149919
1       424998
2       266746
3       244020
4       636056
         ...
1995    295620
1996    580929
1997    476925
1998    161119
1999    482525
Name: Price, Length: 2000, dtype: int64

In [99]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [100]:
x_train

      Area  Bathrooms  Bedrooms  Floors
968   4483          4         4       3
240   1062          3         3       1
819   1422          4         3       1
692   2658          3         2       1
420   3286          4         2       1
...    ...        ...       ...     ...
1130  3483          3         5       3
1294  1747          3         3       2
860   1484          3         2       3
1459  3456          4         5       1
1126  1682          1         2       3

[1600 rows x 4 columns]

In [101]:
x_test

      Area  Bathrooms  Bedrooms  Floors
1860   633          4         1       2
353   3856          1         1       2
1333  1598          4         5       1
905   1705          1         3       2
1289  2564          2         5       3
...    ...        ...       ...     ...
965   1811          3         1       3
1284   794          2         3       2
1739  3540          4         4       2
261   3670          2         5       2
535   3519          1         5       3

[400 rows x 4 columns]

In [102]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [103]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [104]:
x_train

array([[ 1.31408123,  1.31608835,  0.68575834,  1.24226027],
       [-1.31595997,  0.41427192, -0.01488875, -1.23606446],
       [-1.03919445,  1.31608835, -0.01488875, -1.23606446],
       ...,
       [-0.99152928,  0.41427192, -0.71553584,  1.24226027],
       [ 0.52453072,  1.31608835,  1.38640543, -1.23606446],
       [-0.83930825, -1.38936093, -0.71553584,  1.24226027]])

In [105]:
x_test

array([[-1.73524788,  1.26491106, -1.37062124,  0.02755   ],
       [ 0.80324407, -1.44561264, -1.37062124,  0.02755   ],
       [-0.97519677,  1.26491106,  1.46636968, -1.19689453],
       ...,
       [ 0.55435687,  1.26491106,  0.75712195,  0.02755   ],
       [ 0.65674717, -0.54210474,  1.46636968,  0.02755   ],
       [ 0.53781689, -1.44561264,  1.46636968,  1.25199454]])

In [106]:
from xgboost import XGBRegressor

In [107]:
xgb_model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
)

In [108]:
xgb_model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [109]:
y_pred = xgb_model.predict(x_test)

In [110]:
y_pred

array([740072.  , 525783.06, 494802.28, 553962.8 , 561326.56, 638613.7 ,
       515363.1 , 449698.1 , 575381.5 , 659673.2 , 602598.75, 625561.8 ,
       535331.3 , 487196.28, 518027.53, 540551.6 , 480665.06, 543940.7 ,
       609098.8 , 600182.44, 538835.3 , 466638.1 , 540654.1 , 522344.25,
       582348.06, 484293.75, 498446.8 , 447161.5 , 396799.1 , 549251.6 ,
       633101.75, 503144.56, 662766.5 , 562923.4 , 529675.9 , 565161.8 ,
       581388.25, 558282.06, 586450.  , 515483.94, 559426.7 , 569691.06,
       534768.8 , 434481.75, 496840.28, 563558.1 , 590324.6 , 524537.1 ,
       556601.94, 579921.25, 538607.9 , 522180.34, 583323.3 , 595419.25,
       553107.5 , 553150.2 , 534021.75, 527953.  , 529348.6 , 595540.2 ,
       524154.34, 526176.5 , 538905.3 , 502013.5 , 588333.8 , 646861.5 ,
       475540.84, 592374.8 , 522127.1 , 550842.4 , 593120.1 , 648762.6 ,
       601106.9 , 553696.4 , 588423.44, 511357.56, 467985.25, 638262.5 ,
       609784.25, 638116.06, 414766.8 , 559124.4 , 551214.2 , 573582.94,
       465847.62, 481826.06, 534570.25, 510907.34, 535971.1 , 429998.84,
       519911.06, 657773.56, 645050.5 , 510749.53, 640336.7 , 490339.03,
       603246.7 , 533008.2 , 538628.25, 531181.4 , 567139.8 , 544472.25,
       501925.72, 532939.6 , 534358.44, 534100.56, 540654.1 , 549802.5 ,
       657791.94, 553599.25, 641438.  , 548681.8 , 562794.6 , 657773.56,
       582374.3 , 632352.7 , 459197.  , 504243.8 , 600134.4 , 529914.5 ,
       559974.56, 533439.7 , 518474.38, 414675.47, 562545.8 , 547934.06,
       586133.2 , 544978.9 , 559190.75, 617730.7 , 613060.3 , 755315.25,
       526713.1 , 568971.56, 545212.4 , 539619.94, 489673.2 , 496533.22,
       552852.3 , 578312.25, 507839.22, 573606.6 , 505971.75, 503076.25,
       548134.5 , 464869.47, 457557.9 , 479267.88, 604336.4 , 524154.34,
       577518.6 , 506298.38, 485022.66, 531490.75, 569110.3 , 565073.3 ,
       552659.5 , 531206.9 , 565995.06, 568962.2 , 528952.06, 496339.1 ,
       396799.1 , 620226.06, 572572.9 , 450489.47, 551199.06, 565578.06,
       438274.1 , 588243.3 , 527953.  , 578976.6 , 613186.56, 529651.94,
       534729.6 , 552609.6 , 618619.5 , 663080.94, 585379.94, 555783.4 ,
       599032.3 , 563999.  , 489087.7 , 508519.84, 534920.8 , 564656.4 ,
       526949.3 , 518291.34, 545291.7 , 536373.56, 542755.75, 506105.47,
       496696.78, 543406.3 , 539297.56, 555275.  , 604017.5 , 575976.6 ,
       558318.6 , 550730.56, 535476.1 , 524458.  , 618322.06, 559730.7 ,
       501856.28, 469104.5 , 558443.94, 533935.06, 593079.5 , 572816.56,
       621533.8 , 486711.72, 575876.94, 501603.84, 533091.8 , 542770.56,
       517929.2 , 677562.44, 516274.78, 609564.25, 515009.7 , 568265.44,
       620951.06, 607524.7 , 606746.9 , 502971.1 , 501526.78, 513230.5 ,
       482895.94, 602240.3 , 479753.25, 500998.53, 554799.8 , 535437.06,
       687457.3 , 453027.34, 519639.16, 673036.  , 568411.5 , 592792.06,
       550708.1 , 565909.1 , 493206.2 , 526468.56, 533656.56, 499123.2 ,
       599965.56, 520256.7 , 528047.94, 481259.34, 510227.47, 473267.1 ,
       634132.3 , 431004.88, 515772.2 , 324840.75, 516495.78, 557425.9 ,
       488574.22, 542061.75, 506125.8 , 573216.25, 548546.94, 530440.75,
       586920.94, 513787.1 , 622838.06, 529675.9 , 570637.8 , 541234.7 ,
       571213.3 , 616716.56, 580940.3 , 590848.9 , 579409.4 , 511241.53,
       502549.7 , 564457.  , 567847.  , 438643.6 , 404006.47, 524962.8 ,
       509565.12, 624353.3 , 509281.72, 549369.06, 482942.78, 551145.7 ,
       543876.4 , 496906.16, 592621.44, 524863.56, 506560.62, 583285.94,
       587784.06, 538905.3 , 515483.94, 538705.3 , 620998.5 , 574104.3 ,
       564167.  , 633128.5 , 515735.22, 566016.8 , 506105.47, 593120.1 ,
       567565.3 , 595153.  , 564225.3 , 582447.1 , 513230.5 , 519839.3 ,
       661373.44, 533338.56, 590572.44, 545291.7 , 462416.78, 541160.44,
       568762.2 , 498446.8 , 561201.7 , 662766.5 , 617686.06, 518134.78,
       486431.9 , 528843.75, 610415.94, 524025.34, 574844.  , 558729.  ,
       543871.5 , 517878.84, 400987.28, 593943.8 , 696809.75, 534586.5 ,
       510471.94, 594942.94, 527714.44, 551705.6 , 537966.6 , 552811.  ,
       516754.94, 620942.3 , 518113.38, 531483.2 , 553234.56, 465509.6 ,
       633665.56, 555727.25, 535747.9 , 552559.6 , 503144.56, 500825.7 ,
       504471.44, 595872.9 , 545792.44, 541160.44, 638914.4 , 555192.  ,
       549149.8 , 530549.25, 555968.44, 451382.53, 539065.4 , 482131.3 ,
       523327.34, 676757.94, 491134.94, 418847.3 , 524354.75, 551352.75,
       624176.06, 523653.1 , 584551.94, 520357.06, 551319.3 , 492644.4 ,
       562901.9 , 519263.78, 558013.75, 599965.56, 523208.88, 554682.9 ,
       473922.6 , 588613.7 , 578739.1 , 461546.28, 503486.44, 515870.03,
       611517.8 , 399699.75, 486174.44, 637982.8 , 545343.2 , 620463.06,
       559974.56, 543930.8 , 645712.44, 581714.8 ], dtype=float32)

In [111]:
from sklearn.metrics import mean_squared_error, r2_score

In [112]:
print('Mean Squared Error', mean_squared_error(y_test, y_pred))
print('R-2 Score:', r2_score(y_test, y_pred))

Mean Squared Error 83109167104.0
R-2 Score: -0.06825745105743408

In [113]:
new_house = [[2000, 3, 2, 2]] #area, no of bedrooms, no of floors,
new_house_scaled = sc.transform(new_house)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [114]:
new_house_scaled

array([[-0.65857444,  0.36140316, -0.66137351,  0.02755   ]])

In [115]:
print("Estimated House price:",xgb_model.predict(new_house_scaled))

Estimated House price: [496370.12]